import uuidv4 from 'uuid/v4';
import DeckHelper from './DeckHelper';

var data = [
  {
    "name": "Deal Breaker",
    "quantity": 2,
    "description": "none",
    "value": 5,
    "color": "Purple",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Debt Collector",
    "quantity": 2,
    "description": "none",
    "value": 3,
    "color": "Green",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Double the Rent",
    "quantity": 3,
    "description": "none",
    "value": 1,
    "color": "Yelow",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Forced Deal",
    "quantity": 3,
    "description": "none",
    "value": 3,
    "color": "Green",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Hotel",
    "quantity": 3,
    "description": "none",
    "value": 4,
    "color": "Blue",
    "actionCard": true,
    "buildingCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "House",
    "quantity": 3,
    "description": "none",
    "value": 3,
    "color": "Green",
    "actionCard": true,
    "buildingCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "It's My Birthday",
    "quantity": 3,
    "description": "none",
    "value": 2,
    "color": "orange",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Just Say No",
    "quantity": 3,
    "description": "none",
    "value": 4,
    "color": "blue",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Pass Go",
    "quantity": 10,
    "description": "none",
    "value": 1,
    "color": "yellow",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Sly Deal",
    "quantity": 3,
    "description": "none",
    "value": 3,
    "color": "green",
    "actionCard": true,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Baltic Avenue",
    "quantity": 1,
    "description": "none",
    "value": 1,
    "color": "brown",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Mediterranean Avenue",
    "quantity": 1,
    "description": "none",
    "value": 1,
    "color": "brown",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Boardwalk",
    "quantity": 1,
    "description": "none",
    "value": 4,
    "color": "blue",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Park Place",
    "quantity": 1,
    "description": "none",
    "value": 4,
    "color": "blue",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "North Carolina",
    "quantity": 1,
    "description": "none",
    "value": 4,
    "color": "green",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Pacifc Avenue",
    "quantity": 1,
    "description": "none",
    "value": 4,
    "color": "green",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Penn Avenue",
    "quantity": 1,
    "description": "none",
    "value": 4,
    "color": "green",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Conneticut Avenue",
    "quantity": 1,
    "description": "none",
    "value": 1,
    "color": "lightBlue",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Oriental Avenue",
    "quantity": 1,
    "description": "none",
    "value": 1,
    "color": "lightBlue",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Vermont Avenue",
    "quantity": 1,
    "description": "none",
    "value": 1,
    "color": "lightBlue",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "New York Avenue",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "orange",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "St. James Place",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "orange",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Tennessee Avenue",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "orange",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "St. Charles Place",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "purple",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Virginia Avenue",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "purple",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "States Avenue",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "purple",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Short Line Railroad",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "black",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "B & O Railroad",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "black",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Reading Railroad",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "black",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Pennsylvania Avenue",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "black",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Kentucky Avenue",
    "quantity": 1,
    "description": "none",
    "value": 3,
    "color": "red",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Indiana Avenue",
    "quantity": 1,
    "description": "none",
    "value": 3,
    "color": "red",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Illinois Avenue",
    "quantity": 1,
    "description": "none",
    "value": 3,
    "color": "red",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Water Works",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "lightGreen",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Electric Company",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "lightGreen",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Ventnor Avenue",
    "quantity": 1,
    "description": "none",
    "value": 3,
    "color": "yellow",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Marvin Gardens",
    "quantity": 1,
    "description": "none",
    "value": 3,
    "color": "yellow",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Atlantic Avenue",
    "quantity": 1,
    "description": "none",
    "value": 3,
    "color": "yellow",
    "actionCard": false,
    "propertyCard": true,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Blue/Green",
    "quantity": 1,
    "description": "none",
    "value": 3,
    "color": "blue,green",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Light Blue/Brown",
    "quantity": 1,
    "description": "none",
    "value": 1,
    "color": "lightBlue,brown",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Wild Card",
    "quantity": 2,
    "description": "none",
    "value": 0,
    "color": "all",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Orange/Purple",
    "quantity": 2,
    "description": "none",
    "value": 2,
    "color": "orange,purple",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Green/Black",
    "quantity": 1,
    "description": "none",
    "value": 4,
    "color": "green,black",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Light Blue/Black",
    "quantity": 1,
    "description": "none",
    "value": 4,
    "color": "lightBlue,black",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Light Green/Black",
    "quantity": 1,
    "description": "none",
    "value": 2,
    "color": "lightGreen,black",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Yellow/Red",
    "quantity": 2,
    "description": "none",
    "value": 3,
    "color": "yellow,red",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": true,
    "rentCard": false,
    "moneyCard": false
  },
  {
    "name": "Any Rent",
    "quantity": 3,
    "description": "none",
    "value": 3,
    "color": "lightGreen",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": true,
    "moneyCard": false
  },
  {
    "name": "Green/Blue",
    "quantity": 2,
    "description": "none",
    "value": 1,
    "color": "Green/Blue",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": true,
    "moneyCard": false
  },
  {
    "name": "Brown/Light Blue",
    "quantity": 2,
    "description": "none",
    "value": 1,
    "color": "Brown/Light Blue",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": true,
    "moneyCard": false
  },
  {
    "name": "Purple/Orange",
    "quantity": 2,
    "description": "none",
    "value": 1,
    "color": "Purple/Orange",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": true,
    "moneyCard": false
  },
  {
    "name": "Black/lightGreen",
    "quantity": 2,
    "description": "none",
    "value": 1,
    "color": "Black/lightGreen",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": true,
    "moneyCard": false
  },
  {
    "name": "red/Yellow",
    "quantity": 2,
    "description": "none",
    "value": 1,
    "color": "red/Yellow",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": true,
    "moneyCard": false
  },
  {
    "name": "10m",
    "quantity": 1,
    "description": "none",
    "value": 10,
    "color": "Orange",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": true
  },
  {
    "name": "1m",
    "quantity": 6,
    "description": "none",
    "value": 1,
    "color": "Yellow",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": true
  },
  {
    "name": "2m",
    "quantity": 5,
    "description": "none",
    "value": 2,
    "color": "Pink",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": true
  },
  {
    "name": "3m",
    "quantity": 3,
    "description": "none",
    "value": 3,
    "color": "Green",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": true
  },
  {
    "name": "4m",
    "quantity": 3,
    "description": "none",
    "value": 4,
    "color": "Light Blue",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": true
  },
  {
    "name": "5m",
    "quantity": 2,
    "description": "none",
    "value": 5,
    "color": "Purple",
    "actionCard": false,
    "propertyCard": false,
    "wildCard": false,
    "rentCard": false,
    "moneyCard": true
  }
]


const SeedDeck = {
  run: () => {
    let deck = [];
    data.forEach((card) => {
      deck.push(card);
      for(let i = 0; i < card.quantity - 1; i++) {
        uuidv4();
        deck.push({id: uuidv4(),
                  ...card});
      }
    });
    return DeckHelper.shuffle(deck);
  }
}



export default SeedDeck;
